### ISSUE TITLE
Doesn't work with minutes?

### ISSUE THREAD

**Issue by Daniyaldehleh** [alvinwan/timefhuman#22]
Hi All!
Despite the relatively low number of stars, I think this is the best DateTime NLP out there so kudos! 

I think it can really shine itself if supports minutes too to make it more flexible. As currently:

## Input:
`print(timefhuman('2 hours and 30 minutes'))`
## output:
`2021-03-28 02:00:00`

Or
## Input:
`print(timefhuman('30 minutes'))`
## Output:
```
Traceback (most recent call last):
  File "/Users/Daniyal/Desktop/Test/test.py", line 3, in <module>
    print(timefhuman('30 minutes'))
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/main.py", line 58, in timefhuman
    tokens = timefhuman_tokens(string, now)
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/main.py", line 75, in timefhuman_tokens
    tokens = categorize(tokens, now)
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/categorize.py", line 36, in categorize
    tokens = substitute_hour_minute_in_remaining(tokens, now)
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/categorize.py", line 382, in substitute_hour_minute_in_remaining
    time_token = extract_hour_minute(token)
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/categorize.py", line 316, in extract_hour_minute
    return TimeToken(relative_hour=hour, minute=minute, time_of_day=time_of_day)
  File "/Users/Daniyal/opt/anaconda3/lib/python3.8/site-packages/timefhuman/data.py", line 297, in __init__
    assert 0 <= self.hour < 24
AssertionError

```

and 
## Input:
`print(timefhuman('One and half hour'))` or even `print(timefhuman('One hour'))`
## Output:
`[]`

**Comment by rnv812** [comment]
I really need this feature too. Is this project abandoned?
